server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/d_trade?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: wjl131499
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  # 禁用Flyway配置
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # 添加Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  # 添加HTTP消息转换器配置
  http:
    encoding:
      charset: UTF-8
      force: true

# JWT配置
jwt:
  secret: yourSecretKey123456789012345678901234567890
  expiration: 86400000  # 24小时，单位毫秒

# 自定义配置
app:
  upload-dir: uploads/images/

# 日志配置
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.example.d_trade: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: logs/d_trade.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 